name: Deploy HTML to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rename specific HTML file
        run: mv CoursWebInteractif.html index.html

      - name: Copy ONLY index.html via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.ID_ED25519_HTML_COURSES }}
          source: "index.html"
          target: "/var/www/html-starting-courses"
          rm: true

